apiVersion: v1
kind: ConfigMap
metadata:
  name: pci-config
  namespace: {{ include "common.namespace" . }} 
data:
  DMAAPSERVER: message-router.onap
  SDNRSERVICE: '10.143.125.134:8081'
  OOFSERVICE: '10.143.125.134:8081'
  POLICYSERVICE: 'pdp.onap:8081'
  MANAGERAPIKEY: 6nbc3pql61aOUAJf
  MANAGERSECRETKEY: T6I5UkCAV2iOKGNR3NqbXYuJ
  PCIMSAPIKEY: Z4aZNigrgFOIchWN
  PCIMSSECRETKEY: 0W428JKAJdFe6mWERhHjFNdP
  SDNRAPIKEY: sVoE4GjByl3oUJhP
  POLICYAPIKEY: z7iaxSgIwvirkotM
  
